-
  name: Quickstart Configure Playbook
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  collections:
  - solace.pubsub_plus
  module_defaults:
    solace_get_available:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_gather_facts:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      solace_cloud_api_token: "{{ solace_cloud_api_token | default(omit) }}"
      solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"
    solace_vpn:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_queue_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_client_username:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"

  tasks:
    - name: "Pause Until Broker/Service available"
      solace_get_available:
      register: _result
      until: "_result.rc == 0 and _result.is_available == True"
      retries: 25 # 25 * 5 seconds
      delay: 5 # Every 5 seconds"

    - name: Create a new VPN
      solace_vpn:
        name: AI_VPN_1
        settings:
          enabled: true
          dmrEnabled: false

    - name: Create a new queue
      solace_queue:
        name: MRI_SCAN_Q
        msg_vpn: AI_VPN_1
        state: present
        settings:
          accessType: non-exclusive
          egressEnabled: true
          ingressEnabled: true

    - name: Attach subscription to queue -1
      solace_queue_subscription:
        name: "a/b/>"
        queue: MRI_SCAN_Q
        msg_vpn: AI_VPN_1
        state: present

    - name: Attach subscription to queue -2
      solace_queue_subscription:
        name: "c/d/*"
        queue: MRI_SCAN_Q
        msg_vpn: AI_VPN_1
        state: present

    - name: Create Client
      solace_client_username:
        name: MRI_SCANNER_PUB
        msg_vpn: AI_VPN_1
        settings:
          clientProfileName: default
          aclProfileName: default
          password: Intel@123
          enabled: yes
