apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "solace.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "solace.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: ansible-solace
        image: kenbarr/ansible-solace:0.7
        env:
         - name: STATEFULSET_NAME
           value: {{ template "solace.fullname" . }}
         - name: STATEFULSET_NAMESPACE
           valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: 
         - /mnt/disks/solace/ansible_solace.sh
        volumeMounts:
        - name: config-map
          mountPath: /mnt/disks/solace
        - name: secrets
          mountPath: /mnt/disks/secrets
      volumes:
      - name: config-map
        configMap:
          name: {{ template "solace.fullname" . }}
          defaultMode: 0755
      - name: secrets
        secret:
          secretName: {{ template "solace.fullname" . }}-secrets
          defaultMode: 0400              
